### PR TITLE
Add pyinstaller support

### PR DESCRIPTION
**Pull request by baseplate-admin**
Run with 
```
 pyinstaller .\cli.spec   

```

### CODE REVIEW

**Comment by hitblast** [comment]
@baseplate-admin Well uh, I've already found a nicer alternative to pyinstaller. Would you mind taking a look at the recent commits and [Nuitka](https://nuitka.net)?

Instead of depending on hooks and stuff, it directly compiles Python to native C.

**Comment by baseplate-admin** [comment]
> Well uh, I've already found a nicer alternative to pyinstaller. Would you mind taking a look at the recent commits and [Nuitka](https://nuitka.net/)?

Hmm, As expected, its very hard to run nutika on windows.

```python
Nuitka-Options: Used command line options: --clang --onefile avnie/main.py
Nuitka: Starting Python compilation with Nuitka '2.4.5' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                       
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                      
Nuitka: Running C compilation via Scons.
FATAL: Error, Visual Studio required for using ClangCL on Windows.
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

I have both scons and ClangCL installed, but if you can get it running in github actions it will be worth it in my opinion

**Comment by hitblast** [comment]
@baseplate-admin Well then, what'd be your preferable backend for building the app from source? I'd like to chalk out the pros and cons.

**Comment by baseplate-admin** [comment]
> Well then, what'd be your preferable backend for building the app from source? 

Well, in my opinion Nutika > Pyinstaller. But windows er jonno `exe` `nutika` diye toiri kora onek kothin. Tumi jodi `ci/cd` configure krte paro `nutika` run korar jonno, taile `nutika` is the better one.


But `pyinstaller` use kora onek easy and hassle-free. [`Legendary`](https://github.com/derrod/legendary), `HeroicGamesLauncher` er backend `pyinstaller` diye toiri kora.

Check this [reddit thread](https://www.reddit.com/r/learnpython/comments/p9cw5r/pyinstaller_vs_nuitka/), nutika compiled binaries are huggee in nature

**Comment by hitblast** [comment]
@baseplate-admin Well alright, dekhi if I can make it run in CI / CD. Till then, I'll keep this PR opened as both options remain.

**Comment by hitblast** [comment]
@baseplate-admin Alright.

**Comment by baseplate-admin** [comment]
I retired with this

```
poetry run nuitka --onefile avnie/main.py --clean-cache=ccache > log.txt
```

But got this :

[log.txt](https://github.com/user-attachments/files/16528811/log.txt)

**Comment by hitblast** [comment]
@baseplate-admin Just to make things clear, which Python version and clang are you using for producing the build?

**Comment by baseplate-admin** [comment]
> @baseplate-admin Just to make things clear, which Python version and clang are you using for producing the build?

3,12.4, and i am using GCC for the build (it is pulled automatically using `nutika` build)

**Comment by hitblast** [comment]
@baseplate-admin Seems like I have managed to made it work on all of the platforms using CI / CD.
https://github.com/hitblast/avnie/actions/runs/10290285006

**Comment by baseplate-admin** [comment]
Congrats

**Pull request closed without merging**
